version: "3.6"

services:
  transact:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: transact:${ISOLATION_ID}
    volumes:
      - ../..:/project/transact
    environment:
        REDIS_URL: redis://redis:6379
        TEST_MODE: --verbose --release

  redis:
    image: redis
    expose:
      - 6379
